project:
  type: website
  output-dir: docs
website:
  title: "Jhyeok-lee.github.io"
  site-url: "https://jhyeok-lee.github.io"
  site-path: "/"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



